version: '3.9'

services:
  web_api:
    container_name: tax_demo
    build: .
    ports:
      - 32777:32777
    depends_on:
      - "db"
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 6443:6443
    environment:
      POSTGRES_PASSWORD: password_1234

volumes:
  postgres_data: