# Docker compose file to init services

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_TaxDemo
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<PlaceHolder>
    restart: always
    hostname: taxdemoserver

  identitycontextdb:
    image: mcr.microsoft.com/mssql-tools:latest
    restart: no
    command: "/opt/mssql-tools/bin/sqlcmd -S taxdemoserver -l 60 -U sa -P <PlaceHolder> -d master -i /tmp/IdentityContextDB-init.sql"
    depends_on:
        - sqlserver
    volumes:
        - ./IdentityContextDB-init.sql:/tmp/IdentityContextDB-init.sql